# Server Config
server:
  port: 9000
  
# Database Config
spring:
  datasource:
    url: ${AUTH_DATASOURCE_URL}
    username: ${AUTH_DB_USER}
    password: ${AUTH_DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  
# Spring Security Config
logging:
  level:
    org:
      springframework:
        security: trace
  
# Actuator Endpoints
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: health, info

#RSA Keys
rsa:
  private-key: classpath:certificates/private.pem
  public-key: classpath:certificates/public.pem
  key-id: ${JWT_KEY_ID:70d3f8a1-8d6e-42c2-82ce-65691a88f7e5}
