# Application Info
info:
  application:
    name: authorization-server
    description: OAuth2 Authorization Server
    author: Shubham Shinde
    version: '@project.version@'

# Server Config
server:
  port: 9000

# Spring Security Config
logging:
  level:
    org:
      springframework:
        security: trace

# Database Config
spring:
  datasource:
    url: ${AUTH_DATASOURCE_URL}
    username: ${AUTH_DB_USER}
    password: ${AUTH_DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  
# Actuator Endpoints
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: health, info
  info:
    env:
      enabled: true

#RSA Keys
rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
  key-id: ${JWT_KEY_ID:70d3f8a1-8d6e-42c2-82ce-65691a88f7e5}
